### ISSUE TITLE
Chrome extension is logging user out automatically

### ISSUE THREAD

**Issue by gaurangsadekar** [prakhar1989/trackthisshit#16]
If the plugin is not used for a while, it automatically is logging me out without any indication.

**Comment by prakhar1989** [comment]
> "logging me out without any indication."

This is the generally the default scenario. The idea is that the `access_token` provided by facebook expires after a while and hence the extension signs you out. What I can do is, if I have the user's email just let him be signed him until he explicitly signs out.  Will bake that feature in eventually. Not that important. Marking this deferred for now.

**Comment by prakhar1989** [comment]
@gaurangsadekar Here's a fun exercise - Open the console in the extension and paste the following

``` javascript
new Date(parseInt(localStorage.expiryTime))
```

This should tell you when you'll get logged out.
