### ISSUE TITLE
Talking to the API Server

### ISSUE THREAD

**Issue by prakhar1989** [prakhar1989/trackthisshit#2]
- [x] GET
- [x] POST
- [x] DELETE

**Comment by prakhar1989** [comment]
@vinaygaba @gaurangsadekar

[postman collection](https://www.getpostman.com/collections/45d507aa4716b9bcf5b2)

**Comment by prakhar1989** [comment]
@gaurangsadekar @vinaygaba 
Created a simple UI for the extension and completed the `GET` part of talking to the server. You can see the API [mock server](https://github.com/prakhar1989/pricetell/blob/master/chrome-extension/mockserver.py) to see the API I'm expecting. Thoughts?
![image](http://i.imgur.com/pDqTJc5.png)

**Comment by vinaygaba** [comment]
This looks pretty good!

On Wed, Nov 18, 2015 at 2:03 PM, Prakhar Srivastav <notifications@github.com
